### ISSUE TITLE
mnist2d.go

### ISSUE THREAD

**Issue by akihirom2017** [danaugrs/go-tsne#3]
Dear danaugrs

Thank you very much to share your interesting programs.
I am writing this because I have some question regarding to demo script (mnist2d.go)

I have followed the sample code which described in Examples.
I have got an error message.

# command-line-arguments
./mnist2d.go:69:32: cannot use xy literal (type xy) as type plotter.XY in append

Do you know how to solve this issue?

Please let me know.
Thanks

Best wishes

**Comment by danaugrs** [comment]
Hi! Did you alter the example at all? If so can you post the code you are running?
